In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np

In [3]:
import european_call

## Black Scholes

In [4]:
r = 0.01 
sigma = 0.1
K = 90
S0 = 100
ec_bs = european_call.BlackScholes(r=r, sigma=sigma, K=K, S0=S0)

In [5]:
ec_bs.mc_sim_price(T = 1, num_paths = int(1e4), K = None)

tensor([11.5602], device='cuda:0')

In [6]:
ec_bs.exact_price(T=1, K = None)

tensor([11.4770], device='cuda:0', dtype=torch.float64)

In [7]:
ec_bs.fourier_trans_price(T=1, K = None, z_min=0, z_max=np.inf)

11.477015037711325

## Variance Gamma

In [4]:
r = 0.01 
C = 20
G = 40
M = 50
K = 90
S0 = 100
ec_var_gamma = european_call.VarianceGamma(r , C, G, M, K, S0)

In [9]:
ec_var_gamma.mc_sim_price(T=1, num_paths=int(1e6), K = None)

tensor([12.5098], device='cuda:0')

In [10]:
ec_var_gamma.fourier_trans_price(T=1, K = None, z_min=0, z_max=np.inf)

12.527980513692668