In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import mc_simulation
import torch

In [3]:
mc_simulation.gamma_sim(1,1,(5, 10))

tensor([[0.6382, 0.7159, 0.1295, 0.2803, 0.2498, 2.0628, 0.9897, 0.0573, 1.5904,
         0.0180],
        [3.8985, 1.2307, 1.9557, 0.2565, 2.8409, 1.7374, 1.2664, 1.8316, 0.5204,
         1.2449],
        [1.0577, 0.2219, 0.5167, 0.8809, 0.8712, 0.1115, 0.4556, 0.3845, 0.2030,
         0.7460],
        [0.1240, 0.6124, 0.0802, 1.9228, 1.2159, 0.6911, 0.2005, 0.6227, 0.5439,
         0.5565],
        [0.4064, 0.1777, 1.5757, 0.2859, 0.4271, 1.1192, 0.7379, 0.2000, 0.3710,
         0.9232]])

In [9]:
time_points_t = torch.tensor([[0.1, 1,2,3,4],[0.1, 1,2,3,4]], device="cuda").transpose(0,1)

In [10]:
mc_simulation.gamma_process_sim(1,1, time_points_t, device="cuda")

tensor([[3.0797e-03, 1.9021e+00],
        [2.7743e-01, 4.0540e+00],
        [3.2085e-01, 4.0853e+00],
        [9.5113e-01, 5.8505e+00],
        [1.0518e+00, 7.0342e+00]], device='cuda:0')

In [11]:
mc_simulation.var_gamma_sim(20,40,50,time_points_t)

tensor([[-0.0467, -0.0332],
        [-0.0303, -0.2485],
        [-0.1547, -0.3061],
        [-0.2319, -0.3611],
        [-0.6576, -0.5881]], device='cuda:0')